apiVersion: v1
kind: ConfigMap
metadata:
  name: turbo-config-{{ .Release.Name }}
data:
  turbo.config: |-
    {
        "communicationConfig": {
            "serverMeta": {
                "version": "{{ .Values.serverMeta.version }}",
                "turboServer": "{{ .Values.serverMeta.turboServer }}"
            },
            "restAPIConfig": {
                "opsManagerUserName": "{{ .Values.restAPIConfig.opsManagerUserName }}",
                "opsManagerPassword": "{{ .Values.restAPIConfig.opsManagerPassword }}"
            }
        {{- if and .Values.targetConfig.targetName (eq .Values.targetConfig.targetName "Your_k8s_cluster") }}
        }
        {{- else }}
        },
        "targetConfig": {
            "targetName": "{{ .Values.targetConfig.targetName }}"
        }
        {{- end }}
    }