apiVersion: v1
kind: ConfigMap
metadata:
  name: turbo-config-{{ .Release.Name }}
data:
  turbo.config: |-
     {
        "communicationConfig": {
            "serverMeta": {
                "version": "{{ .Values.serverMeta.version }}",
                "turboServer": "{{ .Values.serverMeta.turboServer }}"
            },
            "restAPIConfig": {
                "opsManagerUserName": "{{ .Values.restAPIConfig.opsManagerUserName }}",
                "opsManagerPassword": "{{ .Values.restAPIConfig.opsManagerPassword }}"
            }
        },
        "masterNodeDetectors": {
           "nodeNamePatterns": [ "{{ .Values.masterNodeDetectors.nodeNamePatterns }}" ],
           "nodeLabels": [ {"key": "{{ .Values.masterNodeDetectors.nodeLabelsKey }}", "value": "{{ .Values.masterNodeDetectors.nodeLabelsValue }}"} ]
       },
       "targetConfig": {
           "targetName": "{{ .Values.targetConfig.targetName }}"
       }
    }