apiVersion: v1
kind: ConfigMap
metadata:
  name: turbo-config-{{ .Release.Name }}
data:
  turbo.config: |-
     {
        "communicationConfig": {
            "serverMeta": {
                "version": "{{ .Values.serverMeta.version }}",
                "turboServer": "{{ .Values.serverMeta.turboServer }}"
            },
            "restAPIConfig": {
                "opsManagerUserName": "{{ .Values.restAPIConfig.opsManagerUserName }}",
                "opsManagerPassword": "{{ .Values.restAPIConfig.opsManagerPassword }}"
            }
        },
        "targetConfig": {
            "targetName": "{{ .Values.targetConfig.targetName }}"
        },
        "masterNodeDetectors": {
            "nodeNamePatterns": ["{{.Values.masterNodeDetectors.nodeNamePatterns }}"]
            "nodeLabels": [{"key":"{{.Values.masterNodeDetectors.nodeLabels }}", "value":"{{.Values.masterNodeDetectors.nodeLabelsValue }}"}]
        {{- if .Values.daemonPodDetectors }}
          {{- if and .Values.daemonPodDetectors.namespaces .Values.daemonPodDetectors.podNamePatterns }}
          "daemonPodDetectors": {
              "namespaces": [{{.Values.daemonPodDetectors.namespaces }}]
              "podNamePatterns": ["{{.Values.daemonPodDetectors.podNamePatterns }}"]
          }
          {{- end }}
        {{- end }}
        }
     }